repos:
  # Formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        stages: [pre-commit]
  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        stages: [pre-commit]

  # Basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
    - id: pytest
      name: run tests before push
      entry: bash -c "PYTHONPATH=. pytest"
      language: system
      pass_filenames: false
      stages: [pre-push]
